### ISSUE TITLE
Font not loading

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-style-spec#617]
I am getting a serif font, which I don't think is intentional.

<img width="1488" alt="image" src="https://github.com/maplibre/maplibre-style-spec/assets/649392/e7c766cf-d1a6-4e3a-8488-ce0bc32eee4a">

**Comment by HarelM** [comment]
Good point, I think I saw it too and didn't thought about opening an issue here...
Feel free to take a stab at it.
cc: @birkskyum

**Comment by louwers** [comment]
The contents of `root.module.scss` seem to be entirely absent from the published version of the website.

**Comment by msbarry** [comment]
I noticed this too while working on the docs for the contour source. It looks fine when running `npm run dev` locally, but when I do `npm run build` then `npm run serve` the root CSS is also missing.

**Comment by HarelM** [comment]
I can't find any info on what can cause this issue.
The configuration looks fine according to what I understand from reading the docs.
Might be related to the fact that this is still in beta.
The extra complexity of maintaining all this doesn't seem to worth the trouble.
I'll look into migrating it to simple markdown and serve it using mkdocs or something similar...

**Comment by msbarry** [comment]
Yeah, I agree react and server-side rendering seems like overkill for a static site with very little interactivity, I don't know where I'd start debugging this one.

The only thing I noticed was an exception that got printed while doing the prerendering:

```
⚙  Preparing app for static...
✔ Generated public .output/public                                          vinxi 8:02:50 AM
ℹ Initializing prerenderer                                                 vinxi 8:02:50 AM
ℹ Building Nitro Server (preset: nitro-prerender)                          vinxi 8:02:50 AM
✔ Nitro Server built                                                       vinxi 8:02:51 AM
✔ You can preview this build using npx serve .output/public                vinxi 8:02:51 AM
ℹ Prerendering 1 initial routes with crawler                               vinxi 8:02:52 AM
  ├─ / (56ms)                                                               vinxi 8:02:52 AM
  ├─ /maplibre-style-spec (5ms)                                             vinxi 8:02:52 AM
  ├─ /maplibre-style-spec/root/ (18ms)                                      vinxi 8:02:52 AM
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/nitropack/dist/chunks/prerender.mjs:271:85
    at Array.filter (<anonymous>)
    at extractLinks (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/nitropack/dist/chunks/prerender.mjs:271:70)
    at generateRoute (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/nitropack/dist/chunks/prerender.mjs:180:30)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async runParallel (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/nitropack/dist/chunks/prerender.mjs:250:3)
    at async prerender (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/nitropack/dist/chunks/prerender.mjs:200:3)
    at async createBuild (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/vinxi/lib/build.js:302:2)
    at async Object.run (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/vinxi/bin/cli.mjs:227:5)
    at async runCommand (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (file:///Users/michaelbarry/Projects/maplibre-style-spec/docs/node_modules/citty/dist/index.mjs:445:7)
```

but from what I can tell the root CSS is missing from the build before that step as well.

**Comment by msbarry** [comment]
Ahh sorry I saw stuff like this and assumed it was react https://github.com/maplibre/maplibre-style-spec/blob/85a63c49c471c534cbd1af3c02e075feb1e94f69/docs/src/routes/sources/index.tsx#L74-L83 - when I was editing the docs for contour lines, it seemed awkward to be writing markdown inside jsx components vs. just working in a markdown document. I wonder if markdown with some simple templating system like handlebars that had access to the style spec as a root object would work?

**Comment by HarelM** [comment]
I think the v8.json should provide 80% of the docs, and the rest should be added in markdown files.
I have a prototype running locally, I hope it won't be too long before I can open a PR.

**Comment by birkskyum** [comment]
@msbarry , yeah I guess MDX3 could suffice there to rid of the `<Markdown>`.
